# Change these first
owner: danielauener # Your GitHub organization or username, where this repository lives
repo: status.wptoots.social # The name of this repository

sites:
  - name: wptoots.social
    url: https://wptoots.social

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wptoots.social
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WPToots Mastodon Instance
  introTitle: "**wptoots.social** up or down?"
  introMessage: This is the uptime status page for the [wptoots.social](https://wptoots.social) Mastodon instance. Follow open issues etc. in the (Github Repo)[https://github.com/danielauener/status.wptoots.social].
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
